### What is Numpy?
1. Numpy is a Numeric Python.
2. It is used to perform mahematics operation like trigonometric, statistical, matrix etc.
3. It is python library used working woth arrays.
4. It i Open source library.
5. It is created in 2005 by TRAVIS OLIPHANT.

### How to import numpy?
import numy as np

syntax: np.array([1,2,3])
type(np.array([1,2,3]))

## Numpy Array

In [1]:
import numpy as np

In [2]:
np.array([1,2,'ada'])

array(['1', '2', 'ada'], dtype='<U21')

In [3]:
# upcasting
np.array([1,2,3.4])

array([1. , 2. , 3.4])

In [4]:
# 2-D array 
np.array([[1,2], [3,4]])

array([[1, 2],
       [3, 4]])

In [5]:
type(np.array([[1,2], [3,4]]))

numpy.ndarray

In [7]:
np.array([[1,2], [3,4]], ndmin=4)

array([[[[1, 2],
         [3, 4]]]])

In [8]:
type(np.array([[1,2], [3,4]], ndmin=4))

numpy.ndarray

In [9]:
# converting np array datatype
np.array([1,2,3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [10]:
np.array([1,2,3], dtype=int)

array([1, 2, 3])

In [11]:
np.array([1,2,3], dtype=float)

array([1., 2., 3.])

In [21]:
np.array([(1,2), (4,5)], dtype=[('a','<i2'), ('b', '<i4')]) # i2 and i4 and i8 are indian notation

array([(1, 2), (4, 5)], dtype=[('a', '<i2'), ('b', '<i4')])

In [18]:
x = np.array([(1,2),(3,4)],dtype=[('a','<i2'),('b','<i8')])

In [19]:
x

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [22]:
# access the data using index position
n = np.array([[1,2,3], [4,5,6]])
n

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
n[0]

array([1, 2, 3])

In [24]:
n[0][2]

3

In [25]:
n[1][0]

4

# matrix dataset
### Matrix
It is a datatype. It is a subclass or subset of array.

In [26]:
np.array([[1,2,3],[4,5,6]])


array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
np.mat(np.array([[1,2,3], [4,5,6]]))

matrix([[1, 2, 3],
        [4, 5, 6]])

In [30]:
np.mat('1,2,3;4,5,6')

matrix([[1, 2, 3],
        [4, 5, 6]])

In [31]:
type(np.mat('1,2,3;4,5,6'))

numpy.matrix

## numpy asarray

### Difference between np.array and np.asarray?
There is only one difference i.e. passing the parameter . And that parameter is copy , we are not copy the array in as array. Both are giving same output.

In [32]:
# convert user input into array
a = [[1,2], [3,4]]
np.asarray(a)

array([[1, 2],
       [3, 4]])

#### how to check subclass is true or false using code?

In [34]:
issubclass(np.matrix, np.ndarray)

True

In [35]:
issubclass(np.ndarray, np.matrix)

False

## numpy.asanyarray
if the array is not formated than asanyaary function will convert into any array.

In [36]:
a = [1,2,'b']
np.asanyarray(a)

array(['1', '2', 'b'], dtype='<U21')

## Difference between asanyarray?
It convert the dataset into asanyarray if the data is not a subclass on array. 

In [42]:
a = np.matrix([1,2])
a

matrix([[1, 2]])

In [43]:
np.asanyarray(a)

matrix([[1, 2]])

In [44]:
a = [1,2]
np.asanyarray(a)

array([1, 2])

## Deep Copy and swallo Copy

In [50]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [46]:
y = x

In [47]:
y[1] = 10

In [48]:
x

array([ 1, 10,  3])

In [49]:
y

array([ 1, 10,  3])

#### This is done because both are point on a same location . This is called swallo copy.


In [51]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [52]:
y = np.copy(x)
y

array([1, 2, 3])

In [53]:
y[1] = 10

In [54]:
y

array([ 1, 10,  3])

In [55]:
x

array([1, 2, 3])

#### this is pointing to a different location and independent to each other. this is called deepak copy.

## numpy.fromfunction

In [59]:
np.fromfunction(lambda a,b: a==b, (3,3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [61]:
np.fromfunction(lambda i,j: i*j, (4,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [67]:
# 2-d array
np.fromfunction(lambda i,j: i*j, (3,2), dtype=int)

array([[ 0,  0],
       [ 0,  6],
       [ 0, 12]])

In [1]:
import numpy as np

###  np.arange() and np.linespace()

In [4]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(0,10).reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [25]:
np.linspace(1,10).reshape(10,-1)

array([[ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388],
       [ 1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122],
       [ 2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857],
       [ 3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592],
       [ 4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327],
       [ 5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061],
       [ 6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796],
       [ 7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531],
       [ 8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265],
       [ 9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ]])

In [31]:
# how to axis diagonal element from array
a = np.arange(16).reshape(-1,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [32]:
np.diag(a)

array([ 0,  5, 10, 15])

In [33]:
# k value used to shift the index vaalue from where the diagonal value is taken

np.diag(a,k=2)

array([2, 7])

In [35]:
# in this it will reconstruct the matrix using diagonal values and pull  other values as zero
np.diag(np.diag(a))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [37]:
# using flatten list create 2d array
np.diagflat([[1,2,3],[4,5,6]])

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [42]:
np.tri(3,5,0, dtype=int)

array([[1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0]])

In [44]:
# return the lower triangle of an array
np.tril([[1,2,3],[4,5,6]], k=0)

array([[1, 0, 0],
       [4, 5, 0]])

In [46]:
# for upper triangle
np.triu([[1,2,3],[4,5,6], [8,9,2]], k=0)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 2]])

### random number generation

In [48]:
# it create an array with random number but in range 0 to 1 only ,
np.random.rand(4,3)

array([[0.4342534 , 0.61441103, 0.74994048],
       [0.17396214, 0.17737095, 0.33685848],
       [0.44464656, 0.96324379, 0.0637648 ],
       [0.16464501, 0.85048599, 0.413969  ]])

In [49]:
# this generate the data as standard normal .
# standard normal is defined as number from normal dostribution is 0 and standard deviation is 1.
np.random.randn(4,3)

array([[ 0.00775302, -1.0077874 ,  0.83413945],
       [-0.99413307,  1.13826561, -1.7202023 ],
       [-2.86367893, -1.41371483, -0.93980195],
       [-0.04534204, -0.30913514, -0.62439154]])

In [53]:
# it alsways generate an integer number 
np.random.randint(1,10)

7

In [59]:
# for random integer matrix
np.random.randint(1,10, (4,5))

array([[8, 9, 3, 5, 4],
       [1, 2, 1, 2, 6],
       [7, 9, 8, 1, 9],
       [9, 5, 8, 6, 9]])

In [63]:
# sort the data into ascending order
np.sort(np.random.randint(1,10,(10,2)))

array([[2, 3],
       [7, 8],
       [4, 4],
       [1, 6],
       [2, 8],
       [7, 9],
       [5, 6],
       [1, 4],
       [4, 7],
       [2, 9]])

In [64]:
# sort the data  column and row wise


In [65]:
m = np.random.randint(1,100,25).reshape(5,-1)

In [66]:
m

array([[10, 55, 80, 37, 53],
       [84, 28,  9, 89, 49],
       [45, 80, 75, 43, 19],
       [36, 60,  3, 80,  8],
       [14, 82, 49, 44, 18]])

In [67]:
# axis=1 is used for column
np.sort(m,axis=1)

array([[10, 37, 53, 55, 80],
       [ 9, 28, 49, 84, 89],
       [19, 43, 45, 75, 80],
       [ 3,  8, 36, 60, 80],
       [14, 18, 44, 49, 82]])

In [68]:
np.sort(m,axis=0)

array([[10, 28,  3, 37,  8],
       [14, 55,  9, 43, 18],
       [36, 60, 49, 44, 19],
       [45, 80, 75, 80, 49],
       [84, 82, 80, 89, 53]])

In [69]:
# for sorting the data if axis=1 the data movement in column index and vise versa

In [71]:
# find the maximum value from array
m.max()


89

In [72]:
# find the minimun value from array

m.min()

3

In [75]:
# find the maximum value index from array
print(m)
m.argmax()

[[10 55 80 37 53]
 [84 28  9 89 49]
 [45 80 75 43 19]
 [36 60  3 80  8]
 [14 82 49 44 18]]


8

In [76]:
from numpy.random import randint as ri

### indexing and slicing

In [89]:
a = np.array(ri(10,100,60)).reshape(4,5,3)

In [90]:
a

array([[[23, 23, 46],
        [20, 72, 23],
        [27, 54, 69],
        [76, 25, 78],
        [51, 56, 91]],

       [[69, 85, 87],
        [48, 78, 72],
        [11, 75, 10],
        [86, 27, 94],
        [23, 48, 30]],

       [[60, 39, 50],
        [78, 61, 62],
        [34, 75, 90],
        [40, 34, 65],
        [24, 28, 86]],

       [[36, 28, 46],
        [29, 48, 30],
        [63, 50, 19],
        [20, 99, 39],
        [85, 15, 41]]])

In [91]:
a[0:3,[1,2]]

array([[[20, 72, 23],
        [27, 54, 69]],

       [[48, 78, 72],
        [11, 75, 10]],

       [[78, 61, 62],
        [34, 75, 90]]])

In [95]:
for i in range(4):
    print(a[i][1:3, :])

[[20 72 23]
 [27 54 69]]
[[48 78 72]
 [11 75 10]]
[[78 61 62]
 [34 75 90]]
[[29 48 30]
 [63 50 19]]


### Universal Functions

In [98]:
m1 = np.array(ri(1,10,9)).reshape(3,3)
m1

array([[7, 4, 2],
       [1, 4, 4],
       [1, 1, 6]])

In [115]:
m2 = np.array(ri(10,20,9)).reshape(3,3)
m3 = np.array(ri(10,40,12)).reshape(3,4)
m2

array([[11, 14, 12],
       [14, 13, 13],
       [14, 15, 17]])

In [110]:
m1 * m2 #(index wise multiplication)

array([[70, 56, 26],
       [18, 64, 76],
       [12, 18, 78]])

In [111]:
# matrix multiplication
# matrix multiplication is only done if no of column of first amtrix is equal to the no row of second ,matrix
m1@m2

array([[166, 198, 193],
       [130, 150, 141],
       [100, 138, 110]])

In [116]:
m1@m3

array([[258, 239, 238, 317],
       [266, 231, 154, 175],
       [244, 211, 112, 114]])

In [112]:
m1/m2

array([[0.7       , 0.28571429, 0.15384615],
       [0.05555556, 0.25      , 0.21052632],
       [0.08333333, 0.05555556, 0.46153846]])

In [113]:
m1**2

array([[49, 16,  4],
       [ 1, 16, 16],
       [ 1,  1, 36]])

In [114]:
# find the power of matrix
pow(m1, 4)

array([[2401,  256,   16],
       [   1,  256,  256],
       [   1,    1, 1296]])

#### Only in arange function last perameter is takinga as step

## @made by deepak yadav